import React from 'react';
import { Link } from 'react-router-dom';

const TermsOfService = () => {
  return (
    <div className="bg-[#e9e2d6] min-h-screen text-[#3a2e23]">
      <header className="border-b sticky top-0 bg-[#a87b5d]/80 backdrop-blur-md z-10 playful-shadow">
        <div className="container flex justify-between items-center h-16">
          <div className="flex items-center gap-2">
            <img
              src="https://i.imgur.com/B7ptMnm.png"
              alt="ToonlyAI Logo"
              className="h-12 w-12 object-contain"
              onError={(e) => {
                console.error("Error loading logo:", e);
                e.currentTarget.style.display = 'none';
              }}
            />
            <h1 className="text-2xl font-bold text-white">ToonlyAI</h1>
          </div>
          <a href="/" className="text-white hover:underline">Home</a>
        </div>
      </header>

      <main className="container py-12 max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-6 text-center text-[#6d4c30]">Terms of Service</h1>

        <div className="bg-[#f4efe4]/80 backdrop-blur-sm p-8 rounded-lg playful-shadow playful-border space-y-6">
          <p className="text-sm text-center text-[#8b5e3c]">Last Updated: {new Date().toLocaleDateString()}</p>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">1. Acceptance of Terms</h2>
            <p>
              By accessing and using ToonlyAI (the "Service"), operated by Bhyte Company LLC ("we", "us", or "our"),
              you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms,
              then you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">2. Description of Service</h2>
            <p>
              ToonlyAI provides users with the ability to upload images and transform them into different artistic styles
              using artificial intelligence models provided by third-party services (xAI, OpenAI).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">3. User Conduct and Responsibilities</h2>
            <p>
              You are responsible for the images you upload. You agree not to upload any content that:
            </p>
            <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
              <li>Infringes on any third party's intellectual property rights or other proprietary rights.</li>
              <li>Is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable.</li>
              <li>Contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment.</li>
            </ul>
            <p className="mt-2">
              We reserve the right to remove any content that violates these terms or is otherwise deemed objectionable.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">4. Intellectual Property</h2>
            <p>
              You retain ownership of the original images you upload. By using the Service, you grant us a temporary, non-exclusive, royalty-free license to use, reproduce, and modify the images solely for the purpose of providing the image transformation service to you.
            </p>
             <p className="mt-2">
              The transformed images generated by the Service are provided to you for your use. The underlying AI models and the Service itself are the property of Bhyte Company LLC and/or its licensors (including third-party AI providers).
            </p>
          </section>

           <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">5. Disclaimers and Limitation of Liability</h2>
            <p>
             The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, regarding the accuracy, reliability, or availability of the Service or the results obtained from using the Service. Use of the Service is at your own risk.
            </p>
            <p className="mt-2">
             To the fullest extent permitted by law, Bhyte Company LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) your access to or use of or inability to access or use the service; (b) any conduct or content of any third party on the service; (c) any content obtained from the service; and (d) unauthorized access, use, or alteration of your transmissions or content.
            </p>
             <p className="mt-2">
              The quality and nature of the transformed images depend on the capabilities of the third-party AI models we utilize (xAI, OpenAI). We are not responsible for the specific artistic output or any potential inaccuracies or artifacts in the generated images.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">6. Third-Party Services</h2>
            <p>
             Our Service relies on APIs from third-party providers (xAI, OpenAI). Your use of our Service is also subject to the terms and policies of these providers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">7. Modification of Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any significant changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">8. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction, e.g., the State of Delaware, USA], without regard to its conflict of law provisions.
            </p>
          </section>

           <section>
            <h2 className="text-2xl font-semibold mb-3 text-[#8b5e3c]">9. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at hello@toonlyai.com.
            </p>
          </section>
        </div>
      </main>

       <footer className="mt-16 pt-8 text-center text-sm text-[#5D4037] border-t border-[#a87b5d]/30">
        <div className="flex flex-wrap items-center justify-center space-x-4 mb-4">
          <Link to="/privacy-policy" className="hover:text-[#3a2e23] transition-colors">Privacy Policy</Link>
          <span>•</span>
          <Link to="/terms-of-service" className="hover:text-[#3a2e23] transition-colors">Terms of Service</Link>
          <span>•</span>
          <Link to="/legal" className="hover:text-[#3a2e23] transition-colors">Legal</Link>
        </div>
        
        <p className="text-[#5D4037]/80 mb-3">Built with ❤️ by Bhyte Labs</p>
        
        <div className="mb-4">
          <p className="text-[#5D4037]/70 text-xs">
            We also built: 
            <a href="https://usemidas.app" target="_blank" rel="noopener noreferrer" className="hover:text-[#3a2e23] transition-colors opacity-80 hover:opacity-100 ml-1">Midas</a> <span className="mx-3">•</span> 
            <a href="https://astrae.design" target="_blank" rel="noopener noreferrer" className="hover:text-[#3a2e23] transition-colors opacity-80 hover:opacity-100">Astrae</a> <span className="mx-3">•</span> 
            <a href="https://usepapermind.com" target="_blank" rel="noopener noreferrer" className="hover:text-[#3a2e23] transition-colors opacity-80 hover:opacity-100">Papermind AI</a> <span className="mx-3">•</span> 
            <a href="https://builtwithatlas.com" target="_blank" rel="noopener noreferrer" className="hover:text-[#3a2e23] transition-colors opacity-80 hover:opacity-100">Atlas Labs</a> <span className="mx-3">•</span> 
            <a href="https://studioix.agency" target="_blank" rel="noopener noreferrer" className="hover:text-[#3a2e23] transition-colors opacity-80 hover:opacity-100">Studio IX</a>
          </p>
        </div>
        <p className="mb-4">© {new Date().getFullYear()} ToonlyAI. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default TermsOfService; 